name: Pipeline Build and Push no Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurando a JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construindo o JAR
        run: mvn clean package -DskipTests

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USUARIO }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push no Docker Hub
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: Dockerfile.Spring
          push: true
          tags: |
            pfabianofilho/api-lista_tarefas:v1
